export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const INIT_BLOGS = 'SET_BLOGS'
export const LIKE_BLOG = 'LIKE_BLOG'
export const DELETE_BLOG = 'DELETE_BLOG'

export const LOGIN_USER = 'LOGIN_USER'
